# Generated by Django 3.0.3 on 2020-03-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiningQrcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=45)),
                ('qrcode', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'dining_qrcode',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserFaceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=16, null=True)),
                ('password', models.CharField(max_length=16)),
                ('face_id', models.CharField(blank=True, max_length=31, null=True)),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.SmallIntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=11, unique=True)),
                ('face_feature', models.TextField(blank=True, null=True)),
                ('fpath', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'user_face_info',
                'managed': True,
            },
        ),
    ]
