# Generated by Django 3.0.3 on 2020-03-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0002_uploadimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadimage',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='imgCreated',
            field=models.CharField(default='2020-03-15 10:47:56', max_length=64, verbose_name='创建时间'),
        ),
    ]
