# Generated by Django 3.0.3 on 2020-03-15 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0003_auto_20200315_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='imgCreated',
            field=models.CharField(default='2020-03-15 10:55:39', max_length=64, verbose_name='创建时间'),
        ),
    ]
