# Generated by Django 3.0.3 on 2020-03-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelSystem', '0004_auto_20200315_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phonenumber', models.CharField(max_length=45)),
                ('captcha', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'captcha',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='imgCreated',
            field=models.CharField(default='2020-03-19 19:53:27', max_length=64, verbose_name='创建时间'),
        ),
    ]
